export const SET_ACTIVE_PAGE_FROM_LC = 'forUsersData/SET_ACTIVE_PAGE_FROM_LC'
export const SET_ACTIVE_PAGE_FROM_QUERY_PARAMS = 'forUsersData/SET_ACTIVE_PAGE_FROM__QUERY_PARAMS'
export const SET_CURRENT_PAGE = 'forUsersData/SET_CURRENT_PAGE'

export const SET_SEARCH_REQUEST_FROM_LC = 'forUsersData/SET_SEARCH_REQUEST_FROM_LC'
export const SET_SEARCH_REQUEST_FROM_QUERY_PARAMS = 'forUsersData/SET_SEARCH_REQUEST_FROM__QUERY_PARAMS'
export const SET_SEARCH_REQUEST = 'forUsersData/SET_SEARCH_REQUEST'

export const SET_USERS = 'forUsersData/SET_USERS'

export const SET_TOTAL_USERS_COUNT = 'forUsersData/SET_TOTAL_USERS_COUNT'
export const IS_LOADING_USERS_LIST = 'forUsersData/IS_LOADING_USERS_LIST'

export const CHANGE_FOLLOW_STAT = 'forUsersData/CHANGE_FOLLOW_STAT'
export const SET_NEW_FOLLOW_STAT = 'forUsersData/SET_NEW_FOLLOW_STAT'
export const SET_IS_IN_PROGRESS_CHANGE_FOLLOW_STAT = 'forUsersData/SET_IS_IN_PROGRESS_CHANGE_FOLLOW_STAT'
