export const SET_USERS_LOAD_ERROR = 'forErrorsData/SET_USERS_LOAD_ERROR'
export const SET_USERS_FOLLOW_UNFOLLOW_ERR = 'forErrorsData/SET_USERS_FOLLOW_UNFOLLOW_ERR'

export const SET_FRIENDS_LOAD_ERROR = 'forErrorsData/SET_FRIENDS_LOAD_ERROR'
export const SET_FRIENDS_FOLLOW_UNFOLLOW_ERR = 'forErrorsData/SET_FRIENDS_FOLLOW_UNFOLLOW_ERR'

export const SET_FRIENDS_NAVBAR_ERR = 'forErrorsData/SET_FRIENDS_NAVBAR_ERR'

export const SET_ERR_ON_GET_PROFILE = 'forErrorsData/SET_ERR_ON_GET_PROFILE'
export const SET_ERR_ON_GET_PROFILE_STATUS = 'forErrorsData/SET_ERR_ON_GET_PROFILE_STATUS'
export const SET_ERR_ON_GET_PROFILE_FOLLOW_STAT = 'forErrorsData/SET_ERR_ON_GET_PROFILE_FOLLOW_STAT'

export const SET_ERR_ON_FETCHING_FOLLOW_UNFOLLOW_PROFILE_STAT = 'forErrorsData/SET_ERR_ON_FETCHING_FOLLOW_UNFOLLOW_PROFILE_STAT'

export const SET_ERR_ON_UPDATE_PROFILE_STATUS = 'forErrorsData/SET_ERR_ON_UPDATE_PROFILE_STATUS'
export const SET_ERR_ON_UPDATE_PROFILE_PHOTO = 'forErrorsData/SET_ERR_ON_UPDATE_PROFILE_PHOTO'
export const SET_ERR_ON_UPDATE_PROFILE_MAIN_DATA = 'forErrorsData/SET_ERR_ON_UPDATE_PROFILE_MAIN_DATA'

export const SET_ERR_ON_CHECK_AUTH = 'forErrorsData/SET_ERR_ON_CHECK_AUTH'
