export const GET_FRIENDS_FOR_NAVBAR = 'forFriendsNavbarData/GET_FRIENDS_FOR_NAVBAR'
export const SET_TOTAL_FRIENDS_COUNT = 'forFriendsNavbarData/SET_TOTAL_FRIENDS_COUNT'
export const SET_FRIENDS_FOR_NAVBAR = 'forFriendsNavbarData/SET_FRIENDS_FOR_NAVBAR'
// export const SET_IS_IN_PROGRESS_GET_NAVBAR_FRIENDS = 'forFriendsNavbarData/SET_IS_IN_PROGRESS_GET_NAVBAR_FRIENDS'
