export const SET_ACTIVE_PAGE_FROM_LC = 'forFriendsData/SET_ACTIVE_PAGE_FROM_LC'
export const SET_ACTIVE_PAGE_FROM_QUERY_PARAMS = 'forFriendsData/SET_ACTIVE_PAGE_FROM__QUERY_PARAMS'
export const SET_CURRENT_PAGE = 'forFriendsData/SET_CURRENT_PAGE'

export const SET_SEARCH_REQUEST_FROM_LC = 'forFriendsData/SET_SEARCH_REQUEST_FROM_LC'
export const SET_SEARCH_REQUEST_FROM_QUERY_PARAMS = 'forFriendsData/SET_SEARCH_REQUEST_FROM__QUERY_PARAMS'
export const SET_SEARCH_REQUEST = 'forFriendsData/SET_SEARCH_REQUEST'

export const SET_FRIENDS = 'forFriendsData/SET_USERS'

export const SET_TOTAL_FRIENDS_COUNT = 'forFriendsData/SET_TOTAL_USERS_COUNT'
export const IS_LOADING_FRIENDS_LIST = 'forFriendsData/IS_LOADING_USERS_LIST'

export const CHANGE_FOLLOW_STAT = 'forFriendsData/CHANGE_FOLLOW_STAT'
export const SET_NEW_FOLLOW_STAT = 'forFriendsData/SET_NEW_FOLLOW_STAT'
export const SET_IS_IN_PROGRESS_CHANGE_FOLLOW_STAT = 'forFriendsData/SET_IS_IN_PROGRESS_CHANGE_FOLLOW_STAT'
