export const SEND_MESSAGE = 'forDialogsData/SEND_MESSAGE'
export const IS_IN_PROGRESS_SEND_MESSAGE = 'forDialogsData/IS_IN_PROGRESS_SEND_MESSAGE'

export const GET_DIALOGS_LIST = 'forDialogsData/GET_DIALOGS_LIST'
export const SET_DIALOGS_LIST = 'forDialogsData/SET_DIALOGS_LIST'
export const SET_IS_IN_PROGRESS_LOADING_DIALOGS_LIST = 'forDialogsData/SET_IS_IN_PROGRESS_LOADING_DIALOGS_LIST'
export const INCREASE_SHOWING_PORTION = 'forDialogsData/INCREASE_SHOWING_PORTION'