export const SEND_MESSAGE = 'forDialogsData/SEND_MESSAGE'
export const IS_IN_PROGRESS_SEND_MESSAGE = 'forDialogsData/IS_IN_PROGRESS_SEND_MESSAGE'

export const GET_DIALOGS_LIST = 'forDialogsData/GET_DIALOGS_LIST'
export const SET_DIALOGS_LIST = 'forDialogsData/SET_DIALOGS_LIST'
export const SET_IS_IN_PROGRESS_LOADING_DIALOGS_LIST = 'forDialogsData/SET_IS_IN_PROGRESS_LOADING_DIALOGS_LIST'
export const INCREASE_SHOWING_DIALOGS_PORTION = 'forDialogsData/INCREASE_SHOWING_PORTION'

export const GET_INITIAL_DATA_FOR_MESSAGES_PAGE = 'forDialogsData/GET_INITIAL_DATA_FOR_MESSAGES_PAGE'

export const SET_COMPANION_DATA = 'forDialogsData/SET_COMPANION_DATA'

export const SET_INITIAL_MESSAGES_PORTION = 'forDialogsData/SET_INITIAL_MESSAGES_PORTION'
export const SET_TOTAL_MESSAGES_COUNT = 'forDialogsData/SET_TOTAL_MESSAGES_COUNT'

export const SET_IS_LOADING_MESSAGES_LIST_PRIMARY_DATA = 'forDialogsData/SET_IS_LOADING_MESSAGES_LIST_PRIMARY_DATA'

export const INCREASE_SCROLLED_MESSAGES_PAGE = 'forDialogsData/INCREASE_SCROLLED_MESSAGES_PAGE'
export const SET_NEW_SCROLLED_MESSAGES_PAGE = 'forDialogsData/SET_NEW_SCROLLED_MESSAGES_PAGE'
export const INCREASE_VISIBLE_MESSAGES_PORTION = 'forDialogsData/INCREASE_VISIBLE_MESSAGES_PORTION'
export const SET_IS_LOADING_MESSAGES_PORTION = 'forDialogsData/SET_IS_LOADING_MESSAGES_PORTION'

// export const ADD_SENT_MESSAGE_TO_END = 'forDialogsData/ADD_SENT_MESSAGE_TO_END'

export const DELETE_MESSAGE = 'forDialogsData/DELETE_MESSAGE'
export const ADD_MESSAGE_TO_DELETING = 'forDialogsData/ADD_MESSAGE_TO_DELETING'
export const SET_IS_IN_PROGRESS_DELETING = 'forDialogsData/SET_IS_IN_PROGRESS_DELETING'

export const SPAM_MESSAGE = 'forDialogsData/SPAM_MESSAGE'
export const ADD_MESSAGE_TO_SPAM = 'forDialogsData/ADD_MESSAGE_TO_SPAM'
export const SET_IS_IN_PROGRESS_SPAM = 'forDialogsData/SET_IS_IN_PROGRESS_SPAM'

export const RESTORE_MESSAGE = 'forDialogsData/RESTORE_MESSAGE'
export const REMOVE_MESSAGE_FROM_DELETED_SPAM = 'forDialogsData/REMOVE_MESSAGE_FROM_DELETED_SPAM'
export const SET_IS_IN_PROGRESS_RESTORE = 'forDialogsData/SET_IS_IN_PROGRESS_RESTORE'

export const GET_MESSAGES_NEWER_THAN = 'forDialogsData/GET_MESSAGES_NEWER_THAN'
export const SET_DATE_NEWER_THAN = 'forDialogsData/SET_DATE_NEWER_THAN'
export const SET_IS_IN_PROGRESS_GET_MESSAGES_NEWER_THAN = 'forDialogsData/SET_IS_IN_PROGRESS_GET_MESSAGES_NEWER_THAN'

export const GET_NEW_MESSAGES_COUNT = 'forDialogsData/GET_NEW_MESSAGES_COUNT'
export const SET_NEW_MESSAGES_COUNT = 'forDialogsData/SET_NEW_MESSAGES_COUNT'